# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: verl ci demo-1

on:
  push:
      branches:
        - master
env:
  IMAGE: "verl-ci-cn-beijing.cr.volces.com/whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3"
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.create-runner.outputs.runner_label }}
    steps:
      - name: create mlp customtask
        id: create-runner
        run: |
           # 调用faas创建runner环境
           resp=$(curl -X POST "https://sd10g3clalm04ug7alq90.apigateway-cn-beijing.volceapi.com/runner/create" \
            -d '{"Image": "${{ env.IMAGE }}"}')
           echo $resp
           runner_label=$(echo $resp | jq -r '.runner_label')
           echo "runner_label=$runner_label" >> $GITHUB_OUTPUT
          
          
          

  main-job:
    needs: setup
    # 指定运行在哪个runner
    runs-on: ["${{ needs.setup.outputs.runner-label }}"]
    
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      
      - name: Hello mlp
        run: echo hello mlp
        
      
      - name: list root
        run: ls -ahl /root


      - name: Cleanup
        if: always()
        run: |
          # 调用faas清理runner环境
          curl -X DELETE "https://sd0qig477bam7gokae3i0.apigateway-cn-beijing.volceapi.com/cq_destory" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"runner_id": "${{ needs.setup.outputs.runner-label }}"}'
      
     

          

   


   
